version: '3.1'

services:

  backend:
    image: alberto85/server:113
    ports:
      - 5000:5000
    networks:
      - localnet
    #volumes:
    #  - /tmp/back:/usr/src/app

  frontend:
    image: alberto85/client:112
    ports: 
      - 80:80
    networks:
      - localnet
    #volumes:
    #  - /tmp/front:/usr/src/app
    depends_on:
      - backend
  
  api:
    image: alberto85/api:111
    ports:
      - 2000:2000
    networks:
      - localnet
  
  dbmanager:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - localnet

networks:
  localnet:
    driver: overlay
