version: '3.1'

services:

  backend:
    image: alberto85/server:81
    ports:
      - 5000:3001
    networks:
      - localnet
    #volumes:
    #  - /tmp/back:/usr/src/app

  frontend:
    image: alberto85/client:80
    ports: 
      - 3000:80
    networks:
      - localnet
    #volumes:
    #  - /tmp/front:/usr/src/app
    depends_on:
      - backend

  dbmanager:
    image: adminer
    ports:
      - 8085:8080
    networks:
      - localnet

networks:
  localnet:
    driver: overlay
